#!/bin/sh
oeoeoooea
bspc monitor -d I II III IV V VI VII VIII IX X

rules=(
"Emacs state=tiled"
"Sxiv state=floating"
"mpv state=floating"
"Zathura state=tiled"
"retroarch state=floating"
)

config=(
"focused_border_color #A54242"
"presel_feedback_color #A54242"
"border_width 2"
"window_gap 4"
# "external_rules_command $HOME/.config/bspwm/external_rules"
"split_ratio 0.5"
"borderless_monocle true"
"gapless_monocle true"
)

for i in "${config[@]}"; do bspc config  $i; done
for i in "${rules[@]}" ; do bspc rule -a $i; done

setroot -sc \#282A2E
# setroot ~/Media/AnnasWPs/Flat_Earth_Moon_ym555.png &
# setroot /home/ym/Media/Wallpapers/1546859319019.png

amixer sset Master 100%
xmodmap ~/.Xmodmap
xcape -e "Hyper_L=Escape"
chromium
picom
