#!/bin/sh
sxhkd -m -1 &
bspc monitor -d I II III IV V VI VII VIII IX X &

rules=(
"Emacs state=tiled"
"Zathura state=tiled"
)

config=(
"focused_border_color #A54242"
"presel_feedback_color #A54242"
"border_width 2"
"window_gap 4"
# "external_rules_command $HOME/.config/bspwm/external_rules"
"split_ratio 0.5"
"borderless_monocle true"
"gapless_monocle true"
)

for i in "${config[@]}"; do bspc config  $i & done
for i in "${rules[@]}" ; do bspc rule -a $i & done

# hsetroot -solid \#282A2E &
setroot ~/Media/AnnasWPs/Flat_Earth_Moon_ym555.png &
amixer sset Master 100% &

chromium &
battery &
while :; do mpc idle &> /dev/null; mpd_status &> /dev/null; done &
xmodmap ~/.Xmodmap &
xcape -e "Hyper_L=Escape" &

disown -a

